"""добавили промежуточную таблицу и Hazard

Revision ID: 36c1df7b0b50
Revises: 165a2aba79f8
Create Date: 2022-03-26 11:47:25.869115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c1df7b0b50'
down_revision = '165a2aba79f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hazard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs_to_hazard',
    sa.Column('job', sa.Integer(), nullable=True),
    sa.Column('hazard', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hazard'], ['hazard.id'], ),
    sa.ForeignKeyConstraint(['job'], ['jobs.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs_to_hazard')
    op.drop_table('hazard')
    # ### end Alembic commands ###
